name: Push Docker image

on:
  push:
    branches:
      - main

jobs:
  push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set $DOCKER_ORG and $DOCKER_REPO
        run: |
          echo "DOCKER_ORG=insilica" >> $GITHUB_ENV
          echo "DOCKER_REPO=srvc-hello" >> $GITHUB_ENV

      - name: Build :latest image
        run: docker build -t $DOCKER_ORG/$DOCKER_REPO:latest --file .devcontainer/build/Dockerfile .

      - name: Push image to Docker Hub
        run: docker push $DOCKER_ORG/$DOCKER_REPO:latest
